### ISSUE TITLE
Implement Distance between shapes

### ISSUE THREAD

**Issue by 20chan** [20chan/cirno#5]
Implement distance between shapes, also closest points.

## Expected

```csharp
var circle = new Circle(new Vector(1f, 1f), 1f);
var closest = circle.GetClosestPoint(new Vector(0f, 0f));
Assert.AreEqual(new Vector(0.29f, 0.29f), closest, tolerance: 0.01f);

var line = new Line(new Vector(0f, 0f), new Vector(0f ,1f));
var distance = line.Distance(circle);
Assert.AreEqual(0f, distance);
```

## Todo
- [x] Point - Shape
  - [x] Distance between point and shape
  - [x] Closest point on shape
- [ ] Shape - Shape
  - [ ] Distance between shape and shape
  - [ ] Closest points on two shapes

FYI: `Point - Circle` has been implemented on #6.

**Comment by Guarionex** [comment]
I'll take a look at this

**Comment by Ranner198** [comment]
@Guarionex lmk if you want me to help or anything looks like fun

**Comment by thiamchi** [comment]
#6 I had suggested a solution about the closest point on shape.

**Comment by thiamchi** [comment]
I had added the distance solution in the second commit.

**Comment by Guarionex** [comment]
In my fork/branch I have already solve distance between line and point, circle and point. I have already solve closest point in circle between circle and point and I'm pretty close to closest point in line between line and point. 
https://github.com/Guarionex/cirno/tree/DistanceAndClosestPoint

**Comment by thiamchi** [comment]
@Guarionex had a simpler answer. Probably mine method name can changed to List<Vector> GetIntersectionPoints(Vector point) and find the closest point.

**Comment by 20chan** [comment]
@Guarionex It seems like you did almost, except line and point. After that, send PR and I'll merge conflicts. Thanks.

**Comment by Guarionex** [comment]
I just got line in point closest to another point figured out. Sending PR out now. Going the trigonometric route cause a lot of issues with exponent and squared root on floats. This solution is simple algebra and linear slope equation

**Comment by Guarionex** [comment]
I'm having a very hard time figuring out shape to shape. 
Circle to circle is easy:
- Distance between two centers and subtract both radii. 
- Subtract one radius for closest point
Lines to any shape:
- ???
Using interfaces without type checking for shape
- ???
Someone else feel free to solve it
